const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
const focusOverlay=document.getElementById('focusOverlay');
let currentView='home', currentStageNo=null, mainMap=null, focusMap=null, routeVisible=localStorage.getItem('bc-route')!=='0';
const favorites=new Set(JSON.parse(localStorage.getItem('bc-favs')||'[]'));
const doneStages=new Set(JSON.parse(localStorage.getItem('bc-done')||'[]').map(Number));

const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=s=>{toastEl.textContent=s;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),2400)};
const save=()=>{localStorage.setItem('bc-favs',JSON.stringify([...favorites]));localStorage.setItem('bc-done',JSON.stringify([...doneStages]));};
const mapsUrl=(lat,lon)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(lat+','+lon)}`;
const directionsUrl=(lat,lon)=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+','+lon)}&travelmode=walking`;
const AEMET_STAGE1='https://www.aemet.es/es/eltiempo/prediccion/municipios/grafica/todas/orreaga-roncesvalles-id31211';
const earthUrl=(lat,lon)=>`https://earth.google.com/web/search/${encodeURIComponent(lat+','+lon)}`;
const osmUrl=(lat,lon,z=16)=>`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=${z}/${lat}/${lon}`;
const commonsNearbyUrl=(lat,lon)=>`https://commons.wikimedia.org/wiki/Special:Nearby#/coord/${lat},${lon}`;
const HIGHRES_FRANCES_URL='https://cdn.jsdelivr.net/gh/walktalkmeditate/open-pilgrimages@v1/routes/camino-frances/route.geojson';
let highResStage1Promise=null;

function routeKm(route){let km=0;for(let i=1;i<route.length;i++)km+=havKm(route[i-1],route[i]);return km;}
function geoLines(gj){const out=[];for(const f of gj?.features||[]){const g=f?.geometry;if(!g)continue;if(g.type==='LineString'&&Array.isArray(g.coordinates))out.push(g.coordinates);else if(g.type==='MultiLineString')for(const l of g.coordinates||[])if(Array.isArray(l))out.push(l)}return out;}
function nearestGeoIndex(line,target){let bi=0,bd=Infinity;for(let i=0;i<line.length;i++){const c=line[i],d=(c[1]-target[0])**2+(c[0]-target[1])**2;if(d<bd){bd=d;bi=i}}return{idx:bi,d:bd};}
function extractStage1HighRes(gj){const start=[43.163662,-1.234314],end=[43.008475,-1.319832];let best=null;for(const line of geoLines(gj)){if(line.length<20)continue;const a=nearestGeoIndex(line,start),b=nearestGeoIndex(line,end),score=a.d+b.d;if(!best||score<best.score)best={line,a,b,score}}if(!best)return null;let a=best.a.idx,b=best.b.idx,coords=a<=b?best.line.slice(a,b+1):best.line.slice(b,a+1).reverse();let route=coords.map(c=>[Number(c[1]),Number(c[0])]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));const km=routeKm(route);if(route.length<150||km<20||km>32)return null;return route;}
async function highResStage1(){if(highResStage1Promise)return highResStage1Promise;highResStage1Promise=fetch(HIGHRES_FRANCES_URL,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('route '+r.status);return r.json()}).then(extractStage1HighRes).catch(()=>null);return highResStage1Promise;}
async function upgradeStageRoute(n,map){if(n!==1||!map)return;const route=await highResStage1();if(!route?.length||!map.el?.isConnected)return;map.setRoute(route,false);map.el.dispatchEvent(new CustomEvent('bc-route-upgraded'));toast('Ruta de alta resolución cargada');}

async function loadNearbyPhoto(lat,lon,host){if(!host)return;host.innerHTML='<span class="photo-loading">📷 Buscando foto cercana…</span>';const api='https://commons.wikimedia.org/w/api.php?origin=*&format=json&action=query&generator=geosearch&ggsnamespace=6&ggsradius=1200&ggslimit=6&ggscoord='+encodeURIComponent(lat+'|'+lon)+'&prop=imageinfo&iiprop=url&iiurlwidth=360';try{const r=await fetch(api,{cache:'force-cache'});if(!r.ok)throw 0;const j=await r.json(),pages=Object.values(j?.query?.pages||{}),page=pages.find(x=>x?.imageinfo?.[0]?.thumburl);if(!page)throw 0;const ii=page.imageinfo[0],href=ii.descriptionurl||('https://commons.wikimedia.org/wiki/'+encodeURIComponent(page.title.replace(/ /g,'_')));host.innerHTML=`<a class="route-photo-link" href="${href}" target="_blank" rel="noopener"><img src="${ii.thumburl}" alt="Foto cercana a este punto del Camino"><span>📷 Foto cercana · Wikimedia Commons</span></a>`;}catch{host.innerHTML=`<a class="photo-nearby-link" href="${commonsNearbyUrl(lat,lon)}" target="_blank" rel="noopener">📷 Buscar fotos cercanas</a>`;}}

const STAGE1_ELEVATION_ANCHORS=[
 [43.163668,-1.234870,170.2],[43.152103,-1.242169,265.0],[43.139785,-1.240182,324.4],[43.129554,-1.242366,344.7],
 [43.121261,-1.243408,521.9],[43.115917,-1.237614,726.2],[43.104260,-1.239437,867.0],[43.091490,-1.243935,973.9],
 [43.084113,-1.252092,1086.2],[43.077655,-1.262482,1094.2],[43.068260,-1.269020,1189.7],[43.057277,-1.266668,1231.1],
 [43.047190,-1.264913,1321.4],[43.041941,-1.276306,1247.4],[43.036433,-1.290694,1340.9],[43.028320,-1.295898,1450.0],
 [43.027185,-1.295453,1412.7],[43.026167,-1.305500,1277.4],[43.023584,-1.313762,1188.4],[43.020342,-1.321249,1073.3],
 [43.014461,-1.317398,982.3],[43.008475,-1.319832,953.8]
];

// Datos locales verificados para que Servicios siga siendo útil aunque falle Internet.
// Se ampliarán etapa por etapa; no se inventan teléfonos ni webs.
const LOCAL_SERVICES={1:[
 {type:'alojamiento',name:'Gîte Kayola',lat:43.11780,lon:-1.23810,km:6.4,phone:'+33 6 38 26 97 38',website:'https://www.refuge-orisson.com/',address:'RD 428 · Saint-Michel',note:'Alojamiento de etapa. Reserva recomendable.'},
 {type:'alojamiento',name:'Refuge Orisson',lat:43.1088654,lon:-1.2391822,km:8.0,phone:'+33 6 38 26 97 38',phone2:'+33 5 59 49 13 03',website:'https://www.refuge-orisson.com/',email:'refuge.orisson@wanadoo.fr',address:'RD 428 · Uhart-Cize',note:'Refugio y restaurante en la Ruta de Napoleón.'},
 {type:'alojamiento',name:'Auberge Borda',lat:43.1014507,lon:-1.2389313,km:9.0,phone:'+33 6 61 92 97 43',website:'https://www.aubergeborda.com/',email:'aubergeborda@gmail.com',address:'D428 GR65 · Saint-Michel',hours:'Recepción 14:30–21:00',note:'Alojamiento de montaña con media pensión.'},
 {type:'alojamiento',name:'Albergue de Peregrinos de Roncesvalles',lat:43.0099872,lon:-1.3216338,km:24.2,phone:'+34 948 760 000',phone2:'+34 948 760 029',website:'https://www.alberguederoncesvalles.com/',email:'info@alberguederoncesvalles.com',address:'Real Colegiata · Roncesvalles',note:'Albergue de peregrinos de la Real Colegiata.'},
 {type:'comer',name:'Refuge Orisson · Restaurante',lat:43.1088654,lon:-1.2391822,km:8.0,phone:'+33 6 38 26 97 38',website:'https://www.refuge-orisson.com/',address:'RD 428 · Uhart-Cize',note:'Restaurante del refugio.'},
 {type:'comer',name:'Casa Sabina · Restaurante',lat:43.0102,lon:-1.3195,km:24.2,phone:'+34 948 760 012',website:'https://casasabina.roncesvalles.es/',email:'casasabina@roncesvalles.es',address:'N-135 s/n · Roncesvalles',note:'Bar, restaurante y menú del peregrino.'},
 {type:'farmacia',name:'Pharmacie Arreguy Olaizola',phone:'+33 5 59 37 02 81',address:'27 place Charles de Gaulle · Saint-Jean-Pied-de-Port',query:'Pharmacie Arreguy Olaizola Saint-Jean-Pied-de-Port'},
 {type:'farmacia',name:'Pharmacie NAFARROA',phone:'+33 5 59 37 01 36',address:'7 avenue Jaï Alai · Saint-Jean-Pied-de-Port',query:'Pharmacie NAFARROA Saint-Jean-Pied-de-Port'},
 {type:'salud',name:'Clinique médico-chirurgical Luro',phone:'+33 5 59 37 00 55',address:'Bourg · 64220 Ispoure',website:'https://www.eps-garazi.fr/',query:'Clinique Luro Ispoure'},
 {type:'informacion',name:'Accueil des pèlerins',phone:'+33 5 59 37 05 09',address:'39 rue de la Citadelle · Saint-Jean-Pied-de-Port',website:'https://www.st-jean-pied-de-port.fr/decouvrir/sur-le-chemin-de-st-jacques/',note:'Credencial, sello e información al peregrino.'},
 {type:'informacion',name:'Office de Tourisme',phone:'+33 5 59 37 03 57',address:'14 place Charles de Gaulle · Saint-Jean-Pied-de-Port',website:'https://www.st-jean-pied-de-port.fr/tourisme/office-de-tourisme/'},
 {type:'ayuntamiento',name:'Mairie de Saint-Jean-Pied-de-Port',phone:'+33 5 59 37 00 92',address:'13 place Charles de Gaulle · Saint-Jean-Pied-de-Port',website:'https://www.st-jean-pied-de-port.fr/'},
 {type:'ayuntamiento',name:'Real Colegiata de Roncesvalles · atención al peregrino',phone:'+34 948 760 000',address:'Roncesvalles · Navarra',website:'https://roncesvalles.es/'},
]};

const SERVICE_TYPES=[
 ['🛏','alojamiento','Dormir'],['🍴','comer','Comer'],['💧','agua','Agua'],['✚','farmacia','Farmacia'],['❤','salud','Salud'],['🚕','taxi','Taxi'],
 ['🚌','transporte','Bus/Tren'],['🛒','tienda','Tienda'],['🏧','cajero','Cajero'],['🚻','wc','WC'],['🚲','bici','Bicicleta'],['🟨','informacion','Credencial / info'],['🏛','ayuntamiento','Ayuntamiento']
];

function setActive(k){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===k));}
function stageCard(s){return `<article class="stage-card" data-stage="${s.n}"><div class="num">${s.n}</div><div><h3>${esc(s.from)} → ${esc(s.to)}</h3><div class="meta">${s.km.toFixed(1)} km · ${s.h} · ${esc(s.difficulty)}</div></div><b>›</b></article>`}

function home(){cleanupMaps();currentView='home';currentStageNo=null;setActive('home');app.innerHTML=`<section class="hero"><img class="home-logo" src="buen-camino-logo.png" alt="BUEN CAMINO"><p>Guía gratuita del Camino Francés. Cartografía, desnivel, GPS, servicios, alojamientos y ayuda práctica para el peregrino.</p><span class="pill">V5.4 ESTABLE · SERVICIOS COMPLETOS · MAPA PROFESIONAL · SIN APIS DE PAGO</span></section><section class="section"><div class="section-head"><h2>Las 33 etapas</h2><button class="link-btn" data-nav="stages">Ver todas</button></div>${STAGES.slice(0,5).map(stageCard).join('')}</section><section class="section"><h2>Accesos rápidos</h2><div class="service-grid">${SERVICE_TYPES.slice(0,9).map(x=>`<button class="service-btn" data-quick="${x[1]}"><span>${x[0]}</span>${x[2]}</button>`).join('')}</div></section>`;bindCommon();}
function stages(){cleanupMaps();currentView='stages';setActive('stages');app.innerHTML=`<section class="section"><h2>Etapas del Camino Francés</h2><input id="stageSearch" style="width:100%;padding:12px;border:1px solid #dce3eb;border-radius:12px;margin-bottom:12px" placeholder="Buscar localidad…"> <div id="stageList">${STAGES.map(stageCard).join('')}</div></section>`;bindCommon();document.getElementById('stageSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('stageList').innerHTML=STAGES.filter(s=>(s.from+' '+s.to).toLowerCase().includes(q)).map(stageCard).join('');bindStageCards();};}
function detail(n,tab='resumen'){cleanupMaps();currentStageNo=n;currentView=`detail-${n}`;setActive('stages');const s=STAGES.find(x=>x.n===n);app.innerHTML=`<section class="detail-head"><div class="backline"><button id="backBtn">‹ Volver</button><button id="favBtn">${favorites.has('stage-'+n)?'♥':'♡'}</button></div><div class="eyebrow">ETAPA ${n}</div><h1>${esc(s.from)} → ${esc(s.to)}</h1><div class="detail-stats"><span>🚶 ${s.km.toFixed(1)} km</span><span>◷ ${s.h}</span><span>⛰ +${s.gain} m</span><span>▥ ${esc(s.difficulty)}</span></div></section><div class="detail-tabs">${['resumen','mapa','servicios','alojamientos'].map(t=>`<button data-tab="${t}" class="${t===tab?'active':''}">${t.toUpperCase()}</button>`).join('')}</div><div id="detailBody"></div>`;document.getElementById('backBtn').onclick=stages;document.getElementById('favBtn').onclick=()=>{const k='stage-'+n;favorites.has(k)?favorites.delete(k):favorites.add(k);save();detail(n,tab)};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>detail(n,b.dataset.tab));renderDetail(s,tab);}
function renderDetail(s,tab){const body=document.getElementById('detailBody');if(tab==='resumen'){body.innerHTML=`<section class="section"><div class="stat-grid"><div class="stat">🚶<strong>${s.km.toFixed(1)} km</strong><span>Distancia</span></div><div class="stat">◷<strong>${s.h}</strong><span>Tiempo</span></div><div class="stat">⛰<strong>+${s.gain} m</strong><span>Desnivel</span></div><div class="stat">▥<strong>${esc(s.difficulty)}</strong><span>Dificultad</span></div></div>${s.n===1?'<div class="warning"><strong>⛰ Alta montaña.</strong> Ruta de Napoleón. Revisa meteorología y avisos antes de salir; con mala visibilidad, nieve, hielo o tormenta, prioriza la alternativa segura y las indicaciones oficiales.</div>':''}<h2>Preparación</h2><div class="checklist"><span>💧 Agua y comida</span><button id="summaryAemet" class="check-action">🌦 Meteorología · AEMET</button><span>🔋 Batería / powerbank</span><span>🩹 Botiquín</span><span>🪪 Credencial</span><span>🧥 Capa y abrigo</span></div><h2 style="margin-top:22px">Mapa topográfico</h2><div class="map-toolbar"><button id="summaryRoute" class="map-chip ${routeVisible?'active':''}">🟨 Ruta ${routeVisible?'ON':'OFF'}</button><button id="summaryBig" class="map-chip primary">⛶ AMPLIAR MAPA</button></div><div id="summaryMap" class="bc-map"></div><div class="map-note">El mapa usa un motor propio de BUEN CAMINO: no depende de Leaflet ni de librerías externas. Si OpenTopoMap falla, cada tesela intenta cargar OpenStreetMap como respaldo.</div></section>`;setTimeout(()=>{mainMap=buildStageMap('summaryMap',s.n,false);document.getElementById('summaryRoute').onclick=()=>toggleRoute(document.getElementById('summaryRoute'));document.getElementById('summaryBig').onclick=()=>openFocusMap(s.n);const a=document.getElementById('summaryAemet');if(a)a.onclick=()=>window.open(AEMET_STAGE1,'_blank','noopener');},0);}
else if(tab==='mapa'){body.innerHTML=`<div class="map-workspace"><div class="map-shell"><div id="stageMap" class="bc-map tall"></div><div class="map-floats"><button id="routeFloat" class="map-float ${routeVisible?'active':''}">🟨 RUTA ${routeVisible?'ON':'OFF'}</button><button id="profileFloat" class="map-float">⛰ PERFIL</button><button id="servicesFloat" class="map-float">📌 SERVICIOS</button><button id="gpsFloat" class="map-float">📍 GPS</button><button id="focusFloat" class="map-float main">⛶ MAPA GRANDE</button></div><aside id="stageProfilePanel" class="map-profile-overlay"><div class="elevation-head"><div><span>PERFIL DE DESNIVEL</span><strong id="elevReadout">Toca o desliza</strong></div><button id="stageProfileClose" class="profile-close" aria-label="Ocultar perfil">×</button></div><div id="elevationChart" class="elevation-chart"></div></aside></div></div>`;setTimeout(()=>{mainMap=buildStageMap('stageMap',s.n,false);setupProfile('elevationChart',s.n,mainMap);const panel=document.getElementById('stageProfilePanel'),toggle=()=>panel.classList.toggle('profile-hidden');document.getElementById('routeFloat').onclick=()=>toggleRoute(document.getElementById('routeFloat'));document.getElementById('profileFloat').onclick=toggle;document.getElementById('stageProfileClose').onclick=toggle;document.getElementById('servicesFloat').onclick=()=>showMapServices(s.n,mainMap);document.getElementById('gpsFloat').onclick=()=>locate(mainMap);document.getElementById('focusFloat').onclick=()=>openFocusMap(s.n);},0);}
else if(tab==='servicios'){renderServicesTab(s.n,false)}
else renderServicesTab(s.n,true);
}

function renderServicesTab(n,onlyLodging){const body=document.getElementById('detailBody');const buttons=(onlyLodging?[SERVICE_TYPES[0]]:SERVICE_TYPES);body.innerHTML=`<section class="section"><div class="section-head service-head"><h2>${onlyLodging?'Alojamientos':'Servicios de la etapa'}</h2><div class="service-head-actions"><button id="servicesMapBtn" class="aemet-btn secondary">📍 MAPA</button>${!onlyLodging?'<button id="aemetBtn" class="aemet-btn">🌦 AEMET</button>':''}</div></div><p class="map-note">Teléfono, ubicación, web, email y horario se muestran cuando están verificados. Los botones abren directamente la acción útil en Android.</p><div class="service-grid">${buttons.map(x=>`<button class="service-btn" data-service="${x[1]}"><span>${x[0]}</span>${x[2]}</button>`).join('')}</div><div id="serviceResults"></div></section>`;document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-service]').forEach(x=>x.classList.toggle('active',x===b));showServiceList(n,b.dataset.service)});if(onlyLodging)document.querySelector('[data-service="alojamiento"]')?.click();document.getElementById('servicesMapBtn').onclick=()=>{detail(n,'mapa');setTimeout(()=>{if(mainMap){showMapServices(n,mainMap)}},120)};const a=document.getElementById('aemetBtn');if(a)a.onclick=()=>window.open(AEMET_STAGE1,'_blank','noopener');}
function showServiceList(n,type){const host=document.getElementById('serviceResults');let items=(LOCAL_SERVICES[n]||[]).filter(x=>x.type===type);if(!items.length){host.innerHTML=`<div class="empty"><b>Datos verificados pendientes para esta categoría.</b><p>No vamos a inventar teléfonos ni establecimientos. Se incorporarán etapa por etapa.</p><a href="https://www.openstreetmap.org/search?query=${encodeURIComponent(type+' Camino de Santiago')}" target="_blank" rel="noopener">Buscar en OpenStreetMap</a></div>`;return}host.innerHTML=items.map(serviceCard).join('');}
function serviceIcon(type){return ({alojamiento:'🛏',comer:'🍴',agua:'💧',farmacia:'✚',salud:'❤',taxi:'🚕',transporte:'🚌',tienda:'🛒',cajero:'🏧',wc:'🚻',bici:'🚲',informacion:'🟨',ayuntamiento:'🏛',gps:'📍'})[type]||'📍';}
function serviceCard(x){const q=x.query||x.name;const mapLink=x.lat?mapsUrl(x.lat,x.lon):`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;return `<article class="service-card"><div class="service-title"><span class="service-symbol">${serviceIcon(x.type)}</span><div><span class="kind">${esc(x.type)}</span><h3>${esc(x.name)}</h3></div></div>${x.km!=null?`<p><b>🚶 Km ${Number(x.km).toFixed(1)}</b> del Camino</p>`:''}${x.address?`<p>📍 ${esc(x.address)}</p>`:''}${x.hours?`<p>🕒 ${esc(x.hours)}</p>`:''}${x.note?`<p>ℹ️ ${esc(x.note)}</p>`:''}<div class="service-contact">${x.phone?`<a class="call" href="tel:${esc(x.phone.replace(/\s/g,''))}">📞 ${esc(x.phone)}</a>`:''}${x.phone2?`<a class="call" href="tel:${esc(x.phone2.replace(/\s/g,''))}">📞 ${esc(x.phone2)}</a>`:''}${x.website?`<a class="web" href="${esc(x.website)}" target="_blank" rel="noopener">🌐 Web</a>`:''}${x.email?`<a href="mailto:${esc(x.email)}">✉ Email</a>`:''}<a href="${mapLink}" target="_blank" rel="noopener">📍 Mapa</a>${x.lat?`<a href="${directionsUrl(x.lat,x.lon)}" target="_blank" rel="noopener">🚶 Cómo llegar</a><a href="${earthUrl(x.lat,x.lon)}" target="_blank" rel="noopener">🌍 Earth</a><a href="${osmUrl(x.lat,x.lon)}" target="_blank" rel="noopener">🗺 OSM</a>`:''}</div></article>`;}

/* ---------- Motor de mapa propio ---------- */
function ll2world(lat,lon,z){const s=256*Math.pow(2,z),sin=Math.sin(lat*Math.PI/180);return{x:(lon+180)/360*s,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*s};}
function world2ll(x,y,z){const s=256*Math.pow(2,z),lon=x/s*360-180,n=Math.PI-2*Math.PI*y/s,lat=180/Math.PI*Math.atan(.5*(Math.exp(n)-Math.exp(-n)));return{lat,lon};}
class BCMap{
 constructor(el,opts={}){this.el=typeof el==='string'?document.getElementById(el):el;this.zoom=opts.zoom||11;this.center={lat:opts.lat||43.08,lon:opts.lon||-1.27};this.layer=opts.layer||'topo';this.route=[];this.routeOn=routeVisible;this.services=[];this.extraLines=[];this.selectedRouteIndex=-1;this.onRoutePoint=null;this._raf=0;this.tileNodes=new Map();this.activePointers=new Map();this.panStart=null;this.pinch=null;this.userInteracted=false;this._resizeHandler=()=>this.requestRender();this._build();this._bind();this.render();}
 _build(){this.el.innerHTML='<div class="bc-tiles"></div><svg class="bc-overlay"></svg><div class="bc-markers"></div><div class="bc-map-controls"><button data-z="1" aria-label="Acercar">+</button><button data-z="-1" aria-label="Alejar">−</button></div><button class="bc-layer" title="Cambiar mapa" aria-label="Cambiar tipo de mapa"></button><div class="bc-scale"></div><div class="bc-map-msg">Cargando mapa…</div>';this.tiles=this.el.querySelector('.bc-tiles');this.svg=this.el.querySelector('.bc-overlay');this.markers=this.el.querySelector('.bc-markers');this.scale=this.el.querySelector('.bc-scale');this.msg=this.el.querySelector('.bc-map-msg');this.popup=null;this.updateLayerButton();}
 updateLayerButton(){const b=this.el.querySelector('.bc-layer');if(!b)return;const topo=this.layer==='topo';b.textContent=topo?'🛣 CALLES':'⛰ TOPO';b.title=topo?'Cambiar a mapa de calles':'Cambiar a mapa topográfico';b.setAttribute('aria-label',b.title);b.classList.toggle('streets',!topo);}
 clearTileNodes(){for(const img of this.tileNodes.values())img.remove();this.tileNodes.clear();}
 toggleLayer(){this.layer=this.layer==='topo'?'osm':'topo';if(this.layer==='topo'&&this.zoom>17)this.zoom=17;this.clearTileNodes();this.updateLayerButton();this.render();toast(this.layer==='topo'?'Mapa topográfico':'Mapa de calles');}
 _bind(){this.el.querySelectorAll('[data-z]').forEach(b=>b.onclick=e=>{e.stopPropagation();this.userInteracted=true;this.setZoom(this.zoom+Number(b.dataset.z));});this.el.querySelector('.bc-layer').onclick=e=>{e.stopPropagation();this.userInteracted=true;this.toggleLayer();};
  const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const resetTransforms=()=>{for(const node of [this.tiles,this.svg,this.markers])node.style.transform='';};
  this.el.addEventListener('pointerdown',e=>{if(e.target.closest('button,a,.route-popup'))return;e.preventDefault();this.userInteracted=true;this.closePopup();this.el.setPointerCapture?.(e.pointerId);this.activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.activePointers.size===1){this.panStart={x:e.clientX,y:e.clientY,cp:ll2world(this.center.lat,this.center.lon,this.zoom),dx:0,dy:0};this.pinch=null;}else if(this.activePointers.size===2){const pts=[...this.activePointers.values()];this.panStart=null;resetTransforms();this.pinch={lastDist:Math.max(1,dist(pts[0],pts[1]))};}});
  this.el.addEventListener('pointermove',e=>{if(!this.activePointers.has(e.pointerId))return;e.preventDefault();this.activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.activePointers.size>=2){const pts=[...this.activePointers.values()].slice(0,2),d=Math.max(1,dist(pts[0],pts[1]));if(!this.pinch)this.pinch={lastDist:d};const ratio=d/this.pinch.lastDist;if(ratio>1.15&&this.zoom<18){this.pinch.lastDist=d;this.setZoom(this.zoom+1);}else if(ratio<0.87&&this.zoom>5){this.pinch.lastDist=d;this.setZoom(this.zoom-1);}return;}if(this.panStart){const dx=e.clientX-this.panStart.x,dy=e.clientY-this.panStart.y;this.panStart.dx=dx;this.panStart.dy=dy;for(const node of [this.tiles,this.svg,this.markers])node.style.transform=`translate(${dx}px,${dy}px)`;}});
  const finish=e=>{if(this.activePointers.has(e.pointerId))this.activePointers.delete(e.pointerId);if(this.activePointers.size===0){if(this.panStart){const ll=world2ll(this.panStart.cp.x-this.panStart.dx,this.panStart.cp.y-this.panStart.dy,this.zoom);this.center=ll;}this.panStart=null;this.pinch=null;resetTransforms();this.render();}else if(this.activePointers.size===1){resetTransforms();const p=[...this.activePointers.values()][0];this.panStart={x:p.x,y:p.y,cp:ll2world(this.center.lat,this.center.lon,this.zoom),dx:0,dy:0};this.pinch=null;}};
  this.el.addEventListener('pointerup',finish);this.el.addEventListener('pointercancel',finish);this.el.addEventListener('dblclick',e=>{e.preventDefault();this.setZoom(this.zoom+1)});window.addEventListener('resize',this._resizeHandler,{passive:true});}
 requestRender(){if(this._raf)return;this._raf=requestAnimationFrame(()=>{this._raf=0;this.render();});}
 setZoom(z){const max=this.layer==='topo'?17:18;this.zoom=Math.max(5,Math.min(max,z));this.closePopup();this.render();}
 setRoute(route,fit=true){this.route=route||[];if(fit&&this.route.length)this.fitRoute();else this.render();}
 setRouteVisible(on){this.routeOn=on;this.renderOverlay();}
 fitRoute(){if(!this.route.length)return;const lats=this.route.map(p=>p[0]),lons=this.route.map(p=>p[1]);const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons);this.center={lat:(minLat+maxLat)/2,lon:(minLon+maxLon)/2};const w=Math.max(250,this.el.clientWidth),h=Math.max(250,this.el.clientHeight);for(let z=17;z>=6;z--){const a=ll2world(maxLat,minLon,z),b=ll2world(minLat,maxLon,z);if(Math.abs(b.x-a.x)<w*.86&&Math.abs(b.y-a.y)<h*.82){this.zoom=z;break}}this.render();}
 addServices(items){this.services=items||[];this.renderMarkers();}
 clearServices(){this.services=[];this.renderMarkers();}
 setExtraLines(lines){this.extraLines=lines||[];this.renderOverlay();}
 setSelectedRouteIndex(i){this.selectedRouteIndex=i;this.renderOverlay();}
 render(){const w=this.el.clientWidth,h=this.el.clientHeight;if(w<20||h<20)return;this.renderTiles(w,h);this.renderOverlay();this.renderMarkers();this.renderScale();}
 tileUrl(z,x,y){if(this.layer==='topo'&&z<=17){const subs=['a','b','c'],sub=subs[Math.abs(x+y)%subs.length];return`https://${sub}.tile.opentopomap.org/${z}/${x}/${y}.png`;}return`https://tile.openstreetmap.org/${z}/${x}/${y}.png`;}
 renderTiles(w,h){const z=this.zoom,layer=this.layer,c=ll2world(this.center.lat,this.center.lon,z),ox=c.x-w/2,oy=c.y-h/2,ts=256,n=Math.pow(2,z);const minX=Math.floor(ox/ts),maxX=Math.floor((ox+w)/ts),minY=Math.floor(oy/ts),maxY=Math.floor((oy+h)/ts),needed=new Set();let visibleLoaded=0,total=0;for(let ty=minY;ty<=maxY;ty++){if(ty<0||ty>=n)continue;for(let tx=minX;tx<=maxX;tx++){const wx=((tx%n)+n)%n,key=`${layer}:${z}:${wx}:${ty}`;needed.add(key);total++;let img=this.tileNodes.get(key);if(!img){img=document.createElement('img');img.className='bc-tile';img.alt='';img.decoding='async';img.draggable=false;img.dataset.key=key;img.onload=()=>{img.dataset.loaded='1';if(this.msg)this.msg.style.display='none'};img.onerror=()=>{if(layer==='topo'&&!img.dataset.fallback){img.dataset.fallback='1';img.src=`https://tile.openstreetmap.org/${z}/${wx}/${ty}.png`;return}img.style.opacity='.18'};img.src=this.tileUrl(z,wx,ty);this.tileNodes.set(key,img);this.tiles.appendChild(img);}img.style.left=(tx*ts-ox)+'px';img.style.top=(ty*ts-oy)+'px';if(img.dataset.loaded==='1')visibleLoaded++;}}
  for(const [key,img] of [...this.tileNodes]){if(!needed.has(key)){img.remove();this.tileNodes.delete(key);}}
  this.msg.textContent='Cargando mapa…';this.msg.style.display=visibleLoaded?'none':'block';const seq=(this._tileSeq||0)+1;this._tileSeq=seq;setTimeout(()=>{if(this.msg&&this._tileSeq===seq&&![...this.tileNodes.values()].some(i=>i.dataset.loaded==='1')){this.msg.textContent='El fondo tarda en cargar. La ruta local sigue disponible.'}},1800);}
 pixel(lat,lon){const w=this.el.clientWidth,h=this.el.clientHeight,c=ll2world(this.center.lat,this.center.lon,this.zoom),p=ll2world(lat,lon,this.zoom);return{x:w/2+(p.x-c.x),y:h/2+(p.y-c.y)};}
 renderOverlay(){const w=this.el.clientWidth,h=this.el.clientHeight;this.svg.setAttribute('viewBox',`0 0 ${w} ${h}`);this.svg.innerHTML='';const ns='http://www.w3.org/2000/svg';for(const linePts of this.extraLines){if(!linePts?.length)continue;const pxy=linePts.map(p=>this.pixel(p[0],p[1]));const e=document.createElementNS(ns,'polyline');e.setAttribute('points',pxy.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' '));e.setAttribute('fill','none');e.setAttribute('stroke','#1267d6');e.setAttribute('stroke-width',this.zoom>=13?'4':'3');e.setAttribute('opacity','.9');e.setAttribute('stroke-linecap','round');e.style.pointerEvents='none';this.svg.appendChild(e)}if(!this.routeOn||!this.route.length)return;const pts=this.route.map(p=>this.pixel(p[0],p[1]));const poly=pts.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ');const halo=document.createElementNS(ns,'polyline');halo.setAttribute('points',poly);halo.setAttribute('fill','none');halo.setAttribute('stroke','#fff4bd');halo.setAttribute('stroke-width',this.zoom>=15?'5':'4');halo.setAttribute('stroke-linecap','round');halo.setAttribute('stroke-linejoin','round');this.svg.appendChild(halo);const line=document.createElementNS(ns,'polyline');line.setAttribute('points',poly);line.setAttribute('fill','none');line.setAttribute('stroke','#0a3f86');line.setAttribute('stroke-width',this.zoom>=15?'2.8':'2.2');line.setAttribute('stroke-linecap','round');line.setAttribute('stroke-linejoin','round');this.svg.appendChild(line);const target=this.zoom>=16?102:this.zoom>=14?68:41,step=Math.max(1,Math.ceil(this.route.length/target)),r=this.zoom>=17?10:this.zoom>=16?8.5:this.zoom>=15?7:this.zoom>=13?5.5:4.5;for(let i=0;i<this.route.length;i+=step)this.addRouteCircle(i,r);if((this.route.length-1)%step!==0)this.addRouteCircle(this.route.length-1,r);if(this.selectedRouteIndex>=0){const p=pts[Math.min(this.selectedRouteIndex,pts.length-1)];const c=document.createElementNS(ns,'circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',r+5);c.setAttribute('fill','#ffc400');c.setAttribute('stroke','#e92b2b');c.setAttribute('stroke-width','3');this.svg.appendChild(c);}}
 addRouteCircle(i,r){const ns='http://www.w3.org/2000/svg',p=this.pixel(this.route[i][0],this.route[i][1]),c=document.createElementNS(ns,'circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',r);c.setAttribute('fill','#ffc400');c.setAttribute('stroke','#17345f');c.setAttribute('stroke-width','1.6');c.style.pointerEvents='all';c.style.cursor='pointer';c.addEventListener('click',e=>{e.stopPropagation();this.selectRoutePoint(i,p.x,p.y)});this.svg.appendChild(c);}
 selectRoutePoint(i,x,y){this.selectedRouteIndex=i;this.renderOverlay();this.onRoutePoint?.(i);this.closePopup();const p=this.route[i],samples=buildElevationSamples(1,[this.route]),idx=nearestSample(samples,p[0],p[1]),s=samples[idx];const d=document.createElement('div');d.className='route-popup';d.style.left=x+'px';d.style.top=y+'px';d.innerHTML=`<strong>🟨 ${s?`Km ${s.km.toFixed(1)} · ${Math.round(s.ele)} m`:'Punto de ruta'}</strong><small>${p[0].toFixed(6)}, ${p[1].toFixed(6)}</small><div class="route-photo"></div><div class="popup-actions"><a href="${mapsUrl(p[0],p[1])}" target="_blank" rel="noopener">📍 Maps</a><a href="${earthUrl(p[0],p[1])}" target="_blank" rel="noopener">🌍 Earth</a><a href="${osmUrl(p[0],p[1])}" target="_blank" rel="noopener">🗺 OSM</a><a href="${commonsNearbyUrl(p[0],p[1])}" target="_blank" rel="noopener">📷 Fotos</a></div>`;this.el.appendChild(d);this.popup=d;loadNearbyPhoto(p[0],p[1],d.querySelector('.route-photo'));}
 closePopup(){this.popup?.remove();this.popup=null;}
 renderMarkers(){this.markers.innerHTML='';for(const s of this.services){if(!Number.isFinite(s.lat))continue;const p=this.pixel(s.lat,s.lon),b=document.createElement('button');b.className='bc-marker';b.style.left=p.x+'px';b.style.top=p.y+'px';b.textContent=serviceIcon(s.type);b.title=s.name;b.onclick=e=>{e.stopPropagation();this.closePopup();const d=document.createElement('div');d.className='route-popup service-popup';d.style.left=p.x+'px';d.style.top=p.y+'px';d.innerHTML=`<strong>${serviceIcon(s.type)} ${esc(s.name)}</strong>${s.km!=null?`<small>Km ${Number(s.km).toFixed(1)} del Camino</small>`:''}${s.address?`<small>📍 ${esc(s.address)}</small>`:''}${s.hours?`<small>🕒 ${esc(s.hours)}</small>`:''}${s.phone?`<div class="popup-phone">📞 ${esc(s.phone)}</div>`:''}<div class="popup-actions">${s.phone?`<a href="tel:${s.phone.replace(/\s/g,'')}">📞 Llamar</a>`:''}${s.website?`<a href="${esc(s.website)}" target="_blank" rel="noopener">🌐 Web</a>`:''}<a href="${mapsUrl(s.lat,s.lon)}" target="_blank" rel="noopener">📍 Mapa</a><a href="${directionsUrl(s.lat,s.lon)}" target="_blank" rel="noopener">🚶 Ir</a><a href="${earthUrl(s.lat,s.lon)}" target="_blank" rel="noopener">🌍 Earth</a></div>`;this.el.appendChild(d);this.popup=d};this.markers.appendChild(b);}}
 renderScale(){const lat=this.center.lat,metersPerPixel=156543.03392*Math.cos(lat*Math.PI/180)/Math.pow(2,this.zoom),targetPx=90,raw=metersPerPixel*targetPx;const nice=raw>1000?Math.round(raw/1000)+' km':Math.max(10,Math.round(raw/10)*10)+' m';this.scale.textContent=nice;}
 destroy(){window.removeEventListener('resize',this._resizeHandler);this.activePointers.clear();this.clearTileNodes();this.el.innerHTML='';}
}
function localRoute(n){return (typeof LOCAL_VERIFIED_STAGE_ROUTES!=='undefined'&&LOCAL_VERIFIED_STAGE_ROUTES[n])?LOCAL_VERIFIED_STAGE_ROUTES[n].map(p=>[+p[0],+p[1]]):[];}
function buildStageMap(id,n,services=false){const route=localRoute(n),m=new BCMap(id,{lat:43.08,lon:-1.27,zoom:11,layer:'topo'});m.setRoute(route);m.setRouteVisible(routeVisible);if(services)m.addServices((LOCAL_SERVICES[n]||[]).filter(x=>Number.isFinite(x.lat)));loadMotorways(m,route);setTimeout(()=>upgradeStageRoute(n,m),220);return m;}
async function loadMotorways(map,route){if(!map||!route?.length)return;const lats=route.map(p=>p[0]),lons=route.map(p=>p[1]),pad=.025,s=Math.min(...lats)-pad,w=Math.min(...lons)-pad,n=Math.max(...lats)+pad,e=Math.max(...lons)+pad;const q=`[out:json][timeout:7];way[\"highway\"~\"^(motorway|motorway_link)$\"](${s},${w},${n},${e});out geom;`;const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),6000);try{const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q),{signal:ctrl.signal});if(!r.ok)return;const j=await r.json();const lines=(j.elements||[]).filter(x=>Array.isArray(x.geometry)).map(x=>x.geometry.map(p=>[p.lat,p.lon]));map.setExtraLines(lines)}catch{}finally{clearTimeout(t)}}
function cleanupMaps(){mainMap?.destroy?.();mainMap=null;focusMap?.destroy?.();focusMap=null;if(!focusOverlay.hidden)closeFocusMap();}
function toggleRoute(btn){routeVisible=!routeVisible;localStorage.setItem('bc-route',routeVisible?'1':'0');mainMap?.setRouteVisible(routeVisible);focusMap?.setRouteVisible(routeVisible);if(btn){btn.classList.toggle('active',routeVisible);btn.textContent=`🟨 ${btn.classList.contains('map-float')?'RUTA':'Ruta'} ${routeVisible?'ON':'OFF'}`;}toast(routeVisible?'Ruta visible':'Ruta oculta');}
function showMapServices(n,map){const items=(LOCAL_SERVICES[n]||[]).filter(x=>Number.isFinite(x.lat));if(map.services.length){map.clearServices();toast('Servicios ocultos')}else{map.addServices(items);toast(`${items.length} servicios visibles en el mapa`)}}
function locate(map){if(!navigator.geolocation){toast('GPS no disponible');return}toast('Buscando tu ubicación…');navigator.geolocation.getCurrentPosition(p=>{const {latitude,longitude,accuracy}=p.coords;map.center={lat:latitude,lon:longitude};map.zoom=15;map.render();const s={type:'gps',name:`Tu posición · ±${Math.round(accuracy)} m`,lat:latitude,lon:longitude};map.addServices([...map.services,s]);toast(`GPS ±${Math.round(accuracy)} m`)},()=>toast('No se pudo obtener ubicación. Revisa permisos.'),{enableHighAccuracy:true,timeout:12000,maximumAge:10000});}

function havKm(a,b){const R=6371,r=Math.PI/180,dlat=(b[0]-a[0])*r,dlon=(b[1]-a[1])*r,la1=a[0]*r,la2=b[0]*r,h=Math.sin(dlat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function buildElevationSamples(n,segs){if(n!==1||!segs?.length)return[];const route=segs.flat();if(route.length<2)return[];const cum=[0];for(let i=1;i<route.length;i++)cum[i]=cum[i-1]+havKm(route[i-1],route[i]);const anchors=STAGE1_ELEVATION_ANCHORS.map(a=>{let bi=0,bd=1e9;for(let i=0;i<route.length;i++){const d=(route[i][0]-a[0])**2+(route[i][1]-a[1])**2;if(d<bd){bd=d;bi=i}}return{idx:bi,km:cum[bi],ele:a[2]}}).sort((a,b)=>a.idx-b.idx);const clean=[];for(const a of anchors){if(!clean.length||a.idx>clean.at(-1).idx)clean.push(a)}if(clean.length<2)return[];const elev=km=>{if(km<=clean[0].km)return clean[0].ele;if(km>=clean.at(-1).km)return clean.at(-1).ele;let j=0;while(j<clean.length-2&&clean[j+1].km<km)j++;const a=clean[j],b=clean[j+1],t=(km-a.km)/Math.max(.00001,b.km-a.km);return a.ele+(b.ele-a.ele)*t};const total=cum.at(-1),out=[];let ri=0;for(let k=0;k<180;k++){const km=total*k/179;while(ri<cum.length-2&&cum[ri+1]<km)ri++;const t=(km-cum[ri])/Math.max(.00001,cum[ri+1]-cum[ri]);out.push({km,lat:route[ri][0]+(route[ri+1][0]-route[ri][0])*t,lon:route[ri][1]+(route[ri+1][1]-route[ri][1])*t,ele:elev(km)})}return out;}
function nearestSample(samples,lat,lon){let b=0,bd=1e9;for(let i=0;i<samples.length;i++){const d=(samples[i].lat-lat)**2+(samples[i].lon-lon)**2;if(d<bd){bd=d;b=i}}return b;}
function nearestRoute(route,lat,lon){let b=0,bd=1e9;for(let i=0;i<route.length;i++){const d=(route[i][0]-lat)**2+(route[i][1]-lon)**2;if(d<bd){bd=d;b=i}}return b;}
function setupProfile(id,n,map,readoutId='elevReadout'){const host=document.getElementById(id);if(!host)return;if(!host.dataset.routeUpgradeBound){host.dataset.routeUpgradeBound='1';map.el.addEventListener('bc-route-upgraded',()=>{host.dataset.routeUpgradeBound='';setupProfile(id,n,map,readoutId)},{once:true});}const samples=buildElevationSamples(n,[map.route]);if(!samples.length){host.innerHTML='<div class="empty">Perfil verificado pendiente.</div>';return}const W=600,H=120,pad={l:28,r:8,t:8,b:19},min=Math.min(...samples.map(x=>x.ele)),max=Math.max(...samples.map(x=>x.ele)),x=i=>pad.l+i/(samples.length-1)*(W-pad.l-pad.r),y=e=>pad.t+(max-e)/(max-min||1)*(H-pad.t-pad.b),line=samples.map((p,i)=>`${x(i)},${y(p.ele)}`).join(' '),area=`${pad.l},${H-pad.b} ${line} ${W-pad.r},${H-pad.b}`;host.innerHTML=`<svg class="elevation-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><polygon class="elev-fill" points="${area}"/><polyline class="elev-line" points="${line}"/><line id="elevCursor" class="elev-cursor" x1="${x(0)}" x2="${x(0)}" y1="${pad.t}" y2="${H-pad.b}"/><circle id="elevDot" class="elev-dot" cx="${x(0)}" cy="${y(samples[0].ele)}" r="5"/><text class="elev-label" x="2" y="14">${Math.round(max)} m</text><text class="elev-label" x="2" y="${H-6}">0 km</text><text class="elev-label" x="${W-42}" y="${H-6}">${samples.at(-1).km.toFixed(1)} km</text></svg>`;const svg=host.querySelector('svg'),cur=host.querySelector('#elevCursor'),dot=host.querySelector('#elevDot');const select=(idx,centerMap=false)=>{idx=Math.max(0,Math.min(samples.length-1,idx));const p=samples[idx];cur.setAttribute('x1',x(idx));cur.setAttribute('x2',x(idx));dot.setAttribute('cx',x(idx));dot.setAttribute('cy',y(p.ele));const r=document.getElementById(readoutId);if(r)r.textContent=`Km ${p.km.toFixed(1)} · ${Math.round(p.ele)} m`;const ri=nearestRoute(map.route,p.lat,p.lon);map.setSelectedRouteIndex(ri);if(centerMap){map.center={lat:p.lat,lon:p.lon};map.render();}};map.onRoutePoint=i=>{const p=map.route[i],idx=nearestSample(samples,p[0],p[1]);select(idx,false)};const fromEvent=e=>{const rect=svg.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*W,idx=Math.round((px-pad.l)/(W-pad.l-pad.r)*(samples.length-1));select(idx,false)};svg.addEventListener('pointerdown',e=>{svg.setPointerCapture?.(e.pointerId);fromEvent(e)});svg.addEventListener('pointermove',e=>{if(e.buttons||e.pressure>0)fromEvent(e)});select(0,false);}

function requestLandscape(){
 const btn=document.getElementById('focusRotate');
 if(window.innerWidth>window.innerHeight&&!focusOverlay.classList.contains('force-landscape')){toast('El teléfono ya está en horizontal.');setTimeout(()=>focusMap?.render(),120);return;}
 const forced=focusOverlay.classList.toggle('force-landscape');
 if(btn)btn.textContent=forced?'↕ VERTICAL':'↻ HORIZONTAL';
 setTimeout(()=>focusMap?.render(),220);
}
function openFocusMap(n){focusOverlay.hidden=false;focusOverlay.className='focus-overlay';focusOverlay.innerHTML=`<div class="focus-top"><strong>BUEN CAMINO · MAPA</strong><button id="focusRoute">🟨 Ruta ${routeVisible?'ON':'OFF'}</button><button id="focusProfileToggle">⛰ PERFIL</button><button id="focusServices">📌 Servicios</button><button id="focusRotate">↻ HORIZONTAL</button><button id="focusClose">✕</button></div><div class="focus-body"><div class="focus-map"><div id="focusMapEl" class="bc-map"></div><aside id="focusProfilePanel" class="focus-profile-overlay"><div class="elevation-head"><div><span>DESNIVEL</span><strong id="focusReadout">Toca o desliza</strong></div><button id="focusProfileClose" class="profile-close" aria-label="Ocultar perfil">×</button></div><div id="focusProfile" class="elevation-chart"></div></aside></div></div>`;document.body.style.overflow='hidden';setTimeout(()=>{focusMap=buildStageMap('focusMapEl',n,false);setupProfile('focusProfile',n,focusMap,'focusReadout')},50);const panel=document.getElementById('focusProfilePanel'),toggleProfile=()=>panel.classList.toggle('profile-hidden');document.getElementById('focusRoute').onclick=()=>toggleRoute(document.getElementById('focusRoute'));document.getElementById('focusProfileToggle').onclick=toggleProfile;document.getElementById('focusProfileClose').onclick=toggleProfile;document.getElementById('focusServices').onclick=()=>showMapServices(n,focusMap);document.getElementById('focusClose').onclick=closeFocusMap;document.getElementById('focusRotate').onclick=requestLandscape;}
function closeFocusMap(){focusOverlay.classList.remove('force-landscape');focusMap?.destroy?.();focusMap=null;focusOverlay.hidden=true;focusOverlay.innerHTML='';document.body.style.overflow='';}
window.addEventListener('resize',()=>{if(!focusOverlay.hidden)setTimeout(()=>focusMap?.render(),180)});

function mapView(){cleanupMaps();currentView='map';currentStageNo=1;setActive('map');app.innerHTML=`<section class="section"><h2>Mapa del Camino</h2><p class="map-note">La cartografía se incorporará etapa por etapa con control de calidad. La etapa 1 ya dispone de trazado local. No se dibujan etapas inventadas.</p><div class="map-toolbar"><button id="globalBig" class="map-chip primary">⛶ MAPA GRANDE / HORIZONTAL</button></div><div id="globalMap" class="bc-map tall" style="height:60dvh;min-height:430px"></div></section>`;setTimeout(()=>{mainMap=buildStageMap('globalMap',1,false);document.getElementById('globalBig').onclick=()=>openFocusMap(1)},0);}
function favoritesView(){cleanupMaps();currentView='favorites';setActive('favorites');const list=[...favorites].map(k=>STAGES.find(s=>'stage-'+s.n===k)).filter(Boolean);app.innerHTML=`<section class="section"><h2>Favoritos</h2>${list.length?list.map(stageCard).join(''):'<div class="empty">Todavía no hay etapas favoritas.</div>'}</section>`;bindCommon();}
function myCamino(){cleanupMaps();currentView='mycamino';setActive('mycamino');app.innerHTML=`<section class="section"><h2>Mi Camino</h2><p class="map-note">Marca etapas realizadas.</p>${STAGES.map(s=>`<article class="stage-card" data-done="${s.n}"><div class="num">${doneStages.has(s.n)?'✓':s.n}</div><div><h3>${esc(s.from)} → ${esc(s.to)}</h3><div class="meta">${s.km.toFixed(1)} km</div></div><b>${doneStages.has(s.n)?'Hecha':''}</b></article>`).join('')}</section>`;document.querySelectorAll('[data-done]').forEach(x=>x.onclick=()=>{const n=+x.dataset.done;doneStages.has(n)?doneStages.delete(n):doneStages.add(n);save();myCamino()});}

function openDoubts(){document.getElementById('doubtsBody').innerHTML=`<div class="doubt-card"><strong>⛰ Relieve</strong><p>Revisa curvas de nivel, desnivel y meteorología. En niebla, tormenta, hielo o nieve, sigue avisos oficiales y evita atajos.</p></div><div class="doubt-card"><strong>🥾 Calzado</strong><p>Calzado cómodo, ya usado, adecuado al terreno. Evita estrenar botas el primer día.</p></div><div class="doubt-card"><strong>🎒 Mochila</strong><p>Ligera y bien ajustada. Como orientación, intenta que el peso total no supere aproximadamente el 10 % de tu peso corporal si tu situación física lo permite.</p></div><div class="doubt-card"><strong>🧰 Llevar siempre</strong><p>Agua, algo de comida, capa de lluvia, abrigo ligero, botiquín básico, documentación/credencial, móvil cargado y batería externa.</p></div><div class="doubt-card"><strong>🦶 Pies</strong><p>Calcetines adecuados, pies secos, tratamiento temprano de rozaduras. Si hay dolor importante o lesión, busca atención sanitaria.</p></div><div class="danger-links"><a class="aid" href="https://www.cruzroja.es/guiaprevencion/primeros-auxilios.html" target="_blank">🩹 PRIMEROS AUXILIOS</a><a class="emg" href="tel:112">☎ 112</a></div>`;document.getElementById('doubtsBackdrop').hidden=false;}
function bindStageCards(){document.querySelectorAll('[data-stage]').forEach(x=>x.onclick=()=>detail(+x.dataset.stage));}
function bindCommon(){bindStageCards();document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{detail(1,'servicios');setTimeout(()=>document.querySelector(`[data-service="${b.dataset.quick}"]`)?.click(),40)});}
function navigate(v){if(v==='home')home();else if(v==='stages')stages();else if(v==='map')mapView();else if(v==='favorites')favoritesView();else if(v==='mycamino')myCamino();}
document.querySelectorAll('.bottom-nav [data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.getElementById('brandBtn').onclick=home;document.getElementById('doubtsBtn').onclick=openDoubts;document.getElementById('closeDoubts').onclick=()=>document.getElementById('doubtsBackdrop').hidden=true;document.getElementById('doubtsBackdrop').onclick=e=>{if(e.target.id==='doubtsBackdrop')e.currentTarget.hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
home();
